name: Feature branch CI

on:
  # triggers on push to any branch except main
  push:
    branches-ignore:
      - main

jobs:
  
  test-src:
    # test the code in src/
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test



