name: Feature branch CI

on:
  # triggers on push to any branch except main
  push:
    branches-ignore:
      - main

jobs:
  
  test-src:
    # test the code in src/
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
    - name: Lint check source code
      run: yarn lint
    - name: Confirm build is up-to-date
      run: |
        build_sum=$(sha1sum dist/uncertaintext.js | awk '{ print $1 }')
        yarn build  # updates dist/uncertaintext.js
        rebuild_sum=$(sha1sum dist/uncertaintext.js | awk '{ print $1 }')
        if [ "$rebuild_sum" = "$build_sum" ]; then
          echo "Build is up to date, cool."
        else
          echo "Build is NOT up to date, fail!"
          exit 1
        fi
